# Generated by Django 3.0.4 on 2020-03-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200324_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='country',
        ),
    ]
