# Generated by Django 3.0.4 on 2020-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_timesheetrecord_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='sofreco_contract_no',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='address',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='att_name',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='invoice_company_name',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='name_of_consultant',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='tva_id',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='att_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='invoice_company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='name_of_consultant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='tva_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
