# Generated by Django 3.0.4 on 2020-04-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200325_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetrecord',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
