# Generated by Django 3.0.4 on 2020-04-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_expert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
