# Generated by Django 3.0.4 on 2020-04-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200412_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='address',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='att_name',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='country',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='email',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='identification_no',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='invoice_company_name',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='name_of_consultant',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='service_contract_no',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='subject_of_contract',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='tva_id',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
