# Generated by Django 3.0.4 on 2020-04-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200412_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='details',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='nights_spent_in_cairo',
        ),
        migrations.RemoveField(
            model_name='timesheetrecord',
            name='nights_spent_out_cairo',
        ),
        migrations.AddField(
            model_name='timesheetrecord',
            name='perdiem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetrecord',
            name='day_worked',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
