# Generated by Django 3.0.4 on 2020-04-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200412_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='expert',
        ),
    ]
