# Generated by Django 3.0.4 on 2020-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_timesheet_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='place_of_activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
