# Generated by Django 3.0.4 on 2020-04-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_auto_20200411_2050'),
        ('projects', '0014_project_place_of_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='expert',
        ),
        migrations.AddField(
            model_name='project',
            name='experts',
            field=models.ManyToManyField(related_name='project_experts', to='experts.Expert'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_timesheet', to='experts.Expert'),
        ),
    ]
