# Generated by Django 3.0.4 on 2020-03-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_auto_20200321_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='account_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='address_of_bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='iban',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='name_of_bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='swift_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
