# Generated by Django 3.0.4 on 2020-04-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_auto_20200324_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='vat',
            new_name='email_expert',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='position',
        ),
        migrations.AddField(
            model_name='expert',
            name='daily_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='perdiem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='sur_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='vat_expert',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
